/********************
   HOTEL MANAGEMENT SYSTEM — FULL SQL FILE
   Includes:
   • Database Creation (DDL)
   • Tables (Customer, Room, Booking)
   • Sample Data (DML)
   • Stored Procedures
   • Functions
   • Cursor Example
   • Well-structured and fully commented
*********************/

-- ------------------------------------------------------------
-- 1. CREATE DATABASE
-- ------------------------------------------------------------
DROP DATABASE IF EXISTS HotelDB;
CREATE DATABASE HotelDB;
USE HotelDB;

-- ------------------------------------------------------------
-- 2. TABLE SCHEMAS (DDL)
-- ------------------------------------------------------------

/*===========================
   CUSTOMER TABLE
=============================*/
CREATE TABLE Customer (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(100),
    Email VARCHAR(100),
    Phone VARCHAR(20)
);
--   ROOM TABLE
=============================*/
CREATE TABLE Room (
    RoomID INT PRIMARY KEY AUTO_INCREMENT,
    RoomType VARCHAR(50),
    Price DECIMAL(10,2),
    Status VARCHAR(20) DEFAULT 'Available'
);
--   BOOKING TABLE
=============================*/
CREATE TABLE Booking (
    BookingID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT,
    RoomID INT,
    CheckIn DATE,
    CheckOut DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);
--   INSERT CUSTOMERS
=============================*/
INSERT INTO Customer (FullName, Email, Phone) VALUES
('John Doe', 'john@example.com', '123-456-7890'),
('Mary Smith', 'mary@example.com', '999-555-1111'),
('Adam White', 'adam@example.com', '444-333-2222');

/*===========================
   INSERT ROOMS
=============================*/
INSERT INTO Room (RoomType, Price, Status) VALUES
('Deluxe', 150.00, 'Available'),
('Standard', 100.00, 'Available'),
('Suite', 250.00, 'Available'),
('Premium', 300.00, 'Available');

-- ------------------------------------------------------------
-- 4. STORED PROCEDURES
-- ------------------------------------------------------------

/*=============================================================
   PROCEDURE 1: AddNewBooking
   Inserts a booking and marks the room as booked
===============================================================*/
DELIMITER $$

CREATE PROCEDURE AddNewBooking(
    IN booking_id INT,
    IN cust_id INT,
    IN room_id INT,
    IN checkin DATE,
    IN checkout DATE
)
BEGIN
    INSERT INTO Booking (BookingID, CustomerID, RoomID, CheckIn, CheckOut)
    VALUES (booking_id, cust_id, room_id, checkin, checkout);

    UPDATE Room
    SET Status = 'Booked'
    WHERE RoomID = room_id;
END$$

DELIMITER ;

/*=============================================================
   PROCEDURE 2: CancelBooking
   Removes a booking and marks the room as Available
===============================================================*/
DELIMITER $$

CREATE PROCEDURE CancelBooking(IN booking_id INT)
BEGIN
    DECLARE room_no INT;

    -- Fetch the room number associated with this booking
    SELECT RoomID INTO room_no
    FROM Booking
    WHERE BookingID = booking_id;

    -- Delete the booking
    DELETE FROM Booking WHERE BookingID = booking_id;

    -- Mark room available
    UPDATE Room
    SET Status = 'Available'
    WHERE RoomID = room_no;
END$$

DELIMITER ;

/*=============================================================
   PROCEDURE 3: GetCustomerBookings
   Shows all bookings of a specific customer
===============================================================*/
DELIMITER $$
CREATE PROCEDURE GetCustomerBookings(IN cust_id INT)
BEGIN
    SELECT 
        B.BookingID,
        R.RoomID,
        R.RoomType,
        B.CheckIn,
        B.CheckOut
    FROM Booking B
    JOIN Room R ON B.RoomID = R.RoomID
    WHERE B.CustomerID = cust_id;
END$$

DELIMITER ;

-- ------------------------------------------------------------
-- 5. FUNCTIONS
-- ------------------------------------------------------------

/*=============================================================
   FUNCTION 1: GetRoomRevenue
   Calculates total revenue generated by a room
===============================================================*/
DELIMITER $$

CREATE FUNCTION GetRoomRevenue(room_id INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    DECLARE total_revenue DECIMAL(10,2);

    SELECT SUM(R.Price)
    INTO total_revenue
    FROM Booking B
    JOIN Room R ON B.RoomID = R.RoomID
    WHERE R.RoomID = room_id;

    RETURN IFNULL(total_revenue, 0);
END$$

DELIMITER ;

/*=============================================================
   FUNCTION 2: GetCustomerBookingCount
   Returns number of bookings made by a customer
===============================================================*/
DELIMITER $$

CREATE FUNCTION GetCustomerBookingCount(cust_id INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE total_bookings INT;

    SELECT COUNT(*)
    INTO total_bookings
    FROM Booking
    WHERE CustomerID = cust_id;

    RETURN total_bookings;
END$$

DELIMITER ;

-- ------------------------------------------------------------
-- 6. CURSOR EXAMPLE
-- ------------------------------------------------------------
/*
   Cursor Procedure: ListAllBookings
   Loops through all bookings and prints details
*/
DELIMITER $$

CREATE PROCEDURE ListAllBookings()
BEGIN
    DECLARE done INT DEFAULT FALSE;
    DECLARE b_id INT;
    DECLARE r_id INT;
    DECLARE c_id INT;

    DECLARE booking_cursor CURSOR FOR
        SELECT BookingID, RoomID, CustomerID FROM Booking;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    OPEN booking_cursor;

    read_loop: LOOP
        FETCH booking_cursor INTO b_id, r_id, c_id;

        IF done THEN
            LEAVE read_loop;
        END IF;

        SELECT CONCAT('Booking ID: ', b_id,
                      ' | Room: ', r_id,
                      ' | Customer: ', c_id) AS BookingInfo;
    END LOOP;

    CLOSE booking_cursor;
END$$

DELIMITER ;

-- ------------------------------------------------------------
-- 7. SAMPLE CALLS FOR TESTING
-- ------------------------------------------------------------

/* Add a booking */
CALL AddNewBooking(10, 1, 2, '2025-08-20', '2025-08-25');

/* Cancel a booking */
-- CALL CancelBooking(10);

/* View bookings of customer */
-- CALL GetCustomerBookings(1);

/* Check revenue */
-- SELECT GetRoomRevenue(2) AS Revenue;

/* Count customer bookings */
-- SELECT GetCustomerBookingCount(1) AS TotalBookings;

/* Run cursor example */
-- CALL ListAllBookings();

-- ------------------------------------------------------------
-- END OF FILE
-- ------------------------------------------------------------
